version: "3"
volumes:
  code-server:
    driver: local
  works:
    driver: local
services:
  code-server:
    image: ubudev/code-server:19.04
    build:
      context: ./docker/code-server
    hostname: ubudev-1904
    ports:
      - "443:8443"
    volumes:
      - "~/.ssh/id_rsa:/home/mine/.ssh/id_rsa"
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "code-server:/home/mine/.local/share/code-server"
      - "works:/home/mine/works"
    env_file:
      - server.env
