version: "3.7"
services:
  ubudev:
    image: ubudev/server:19.04
    build:
      context: ./docker
    hostname: ubudev-1904
    ports:
      - "15900:5900"
      - "18443:8443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "~/.local/share/code-server:/home/mine/.local/share/code-server"
      - "~/.ssh/id_rsa:/home/mine/.ssh/id_rsa"
      - "~/Workspace:/home/mine/Workspace"
    env_file:
      - server.env
