version: "3"
volumes:
  ubudev_code-server:
    external: true
  ubudev_works:
    external: true
services:
  volume-backup:
    image: ubudev/volume-backup:latest
    build:
      context: ./docker/volume-backup
    volumes:
      - "ubudev_code-server:/volume/code-server"
      - "ubudev_works:/volume/works"
      - "./backup:/backup"
